In [3]:
import numpy as np
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
std_df = pd.read_csv("/content/drive/MyDrive/kwukdt/data-analysis/data-collection/average_class_size.csv", encoding="UTF-8")
display(std_df)

    항목    시점  서울특별시  제주특별자치도
0   전체  2011  29.36    28.88
1   전체  2012  28.63    28.09
2   전체  2013  27.81    27.26
3   전체  2014  26.96    26.46
4   전체  2015  26.19    25.97
5   전체  2016  25.36    25.53
6   전체  2017  24.60    25.25
7   전체  2018  23.76    24.97
8   전체  2019  22.96    24.47
9   전체  2020  22.45    24.15
10  전체  2021  22.47    23.70
11  전체  2022  22.03    23.36
12  전체  2023  21.84    22.72
13  전체  2024  21.77    22.36
14  전체  2025  21.68    21.63

In [9]:
std_df.shape

(15, 4)

In [10]:
car_df = pd.read_csv("/content/drive/MyDrive/kwukdt/data-analysis/data-collection/government-certified_fuel_economy.csv", encoding="UTF-8")
display(car_df)

,모델명,제조(수입사),차종,유형,복합_연비,1회충전주행거리,도심_연비,고속도로_연비,등급
0,베프(VEV),Luqi Intellgent Technology Co Ltd,화물차,일반형,6,67.0,5.9,6.2,초소형
1,MASADA QQ 2밴,체리자동차,화물차,밴형,6.3,100.0,6.4,6.1,초소형
2,CEVO-C SE 1인승 밴형,주식회사 쎄보모빌리티,승용차,일반형,6.3,69.0,6.7,5.8,초소형
3,포텐스,(주)진우에스엠씨,화물차,일반형,4.5,57.0,5.4,3.8,초소형
4,D2C(D2C13),쎄미시스코,화물차,화물,5.4,79.0,6,4.8,초소형
...,...,...,...,...,...,...,...,...,...
3988,"K7 2.4하이브리드 (17""타이어) (15)",기아,승용차,일반형,16.2,NaN,16.1,16.2,1등급
3989,니로 1.6GDI 하이브리드_18''타이어 (15),기아,승용차,기타형,17.1,NaN,17.7,16.4,1등급
3990,니로 1.6GDI 하이브리드_16''타이어 (15),기아,승용차,기타형,19.5,NaN,20.1,18.7,1등급
3991,아이오닉 1.6GDI 하이브리드 6DCT_17''타이어,현대,승용차,일반형,20.2,NaN,20.4,19.9,1등급
3992,아이오닉 1.6GDI 하이브리드 6DCT_15''타이어,현대,승용차,일반형,22.4,NaN,22.5,22.2,1등급

In [11]:
car_df.shape

(3993, 9)

In [12]:
display(car_df.describe())

         1회충전주행거리
count  606.000000
mean   307.240264
std    163.880204
min      7.000000
25%    153.000000
50%    370.500000
75%    437.750000
max    739.000000